<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td height="20" valign="bottom" bgcolor="#CCCCCC">&nbsp;<span class="arrow9px">6</span> <font color="#FFFFFF"><b>权限管理</b></font></td>
    </tr>
	
    <tr>
      <td height="25" id="s1"><span class="arrow9px" id="a1">4</span> <span id="f1"><a href="../ts_query/env_access_privi_query.jsp" target="ifra1">环境登陆权限查询</a></span></td>
    </tr>
    <tr>
      <td background="images/bg_line.gif"><img src="images/bg_line.gif" width="3" height="1"></td>
    </tr>
	
    <tr>
      <td height="25" valign="middle" id="s2"><span class="arrow9px" id="a2">4</span> <span id="f2"><a href="../ts_query/env_access_privi_do.jsp" target="ifra1">环境登陆权限赋予</a></span></td>
    </tr>
    <tr>
      <td background="images/bg_line.gif"><img src="images/bg_line.gif" width="3" height="1"></td>
    </tr>

    <tr>
      <td height="25" valign="middle" id="s2"><span class="arrow9px" id="a2">4</span> <span id="f2"><a href="../ts_query/certificate_do.jsp" target="ifra1">证书管理</a></span></td>
    </tr>
    <tr>
      <td background="images/bg_line.gif"><img src="images/bg_line.gif" width="3" height="1"></td>
    </tr>

    <tr>
      <td height="25">&nbsp;</td>
    </tr>
  </table>