<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td height="20" valign="bottom" bgcolor="#CCCCCC">&nbsp;<span class="arrow9px">6</span> <font color="#FFFFFF"><b>权限管理</b></font></td>
    </tr>
    <tr>
      <td height="25" id="s1"><span class="arrow9px" id="a1">4</span> <span id="f1"><a href="../ext_db_access_privi.jsp" target="ifra1">数据库权限赋予</a></span></td>
    </tr>
    <tr>
      <td background="images/bg_line.gif"><img src="images/bg_line.gif" width="3" height="1"></td>
    </tr>
      <tr>
      <td height="25" id="s1"><span class="arrow9px" id="a1">4</span> <span id="f1"><a href="../ext_db_privi_query.jsp" target="ifra1">数据库权限回收</a></span></td>
    </tr>
    <tr>
      <td background="images/bg_line.gif"><img src="images/bg_line.gif" width="3" height="1"></td>
    </tr>
	<tr>
      <td height="25" id="s1"><span class="arrow9px" id="a1">4</span> <span id="f1"><a href="../ext_env_access_privi.jsp" target="ifra1">应用权限赋予</a></span></td>
    </tr>
    <tr>
      <td background="images/bg_line.gif"><img src="images/bg_line.gif" width="3" height="1"></td>
    </tr>
		<tr>
      <td height="25" id="s1"><span class="arrow9px" id="a1">4</span> <span id="f1"><a href="../ext_env_access_pri_query.jsp" target="ifra1">应用权限回收</a></span></td>
    </tr>
    <tr>
      <td background="images/bg_line.gif"><img src="images/bg_line.gif" width="3" height="1"></td>
    </tr>
    <tr>
      <td height="25">&nbsp;</td>
    </tr>
</table>