<table border="0" cellpadding="0" cellspacing="0" align="center">
    <tr>
      <td align="center"><a href="main3.jsp" class="toplink">搭建流程</a>　<span class="style1">|</span>　<a href="main1.jsp" class="toplink">应用环境</a>　<span class="style1">|</span>　<a href="main2.jsp" class="toplink">数据库</a>　<span class="style1">|</span>　<a href="main4.jsp" class="toplink">备份管理</a>　<span class="style1">|</span>　<a href="main5.jsp" class="toplink">权限管理</a>　<span class="style1">|</span>　<a href="main6.jsp" class="toplink">资产管理</a>　<span class="style1">|</span>　<a href="main7.jsp" class="toplink">其它信息</a>　</td>
    </tr>
</table>
